# Generated by Django 5.1.6 on 2025-03-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='platform',
        ),
        migrations.DeleteModel(
            name='StreamPlatform',
        ),
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
